[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
test = "contracts/test"
remappings = [
    '@openzeppelin/contracts/=contracts/lib/openzeppelin-contracts/contracts/',
    'forge-std/=contracts/lib/forge-std/src/',
    'erc4626-tests/=contracts/lib/openzeppelin-contracts/lib/erc4626-tests/',
    'halmos-cheatcodes/=contracts/lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# =============================================================================
# RPC ENDPOINTS
# =============================================================================
[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base_mainnet = "${BASE_MAINNET_RPC_URL}"

# =============================================================================
# ETHERSCAN CONFIGURATION (for contract verification)
# =============================================================================
[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
